### ISSUE TITLE
Design difference between Source Han Sans K and Source Han Serif K 3

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#61] opened 2017-05-19 07:40 UTC
In some characters that relate to KS X 1002, I found some glyphs that have different character form between Source Han Sans and Source Han Serif.
I refered to sources such as Unihan’s kIRG_KSource to distinguish whether they relate to KS X 1002.  I apologize in advance if there are non-related characters included. 
U+4E7C 乼, U+5070 偰, U+5125 儥, U+58B0 墰, U+5C14 尔, U+60C6 惆, U+6424 搤, U+6D2C 洬, U+6E54 湔, U+7662 癢, U+83C2 菂, U+83DF 菟, U+86C0 蛀, U+8729 蜩, U+8CD9 賙, U+90DC 郜, U+970C 霌, U+9714 霔, U+9746 靆, U+99B0 馰, U+9C4F 鱏, U+9D69 鵩, U+9EF7 黷

![kr_diff3](https://cloud.githubusercontent.com/assets/21096794/26237752/5f0bfeec-3cb1-11e7-84c9-a4b84b3f2fb3.JPG)

**Comment by kenlunde** [comment] 2017-05-19 13:20
I can confirm that they are all KS X 1002 ideographs.

**Comment by hfhchan** [comment] 2017-05-19 17:03
Hmmm.  For most of these ideographs in Source Han Serif, a more traditional glyph in-line with Korean conventions had been chosen.  However, since they are out of the scope of official coverage by Source Han Sans/Serif, they are "supposed" to be following JP/CN's style.

I am not quite sure these glyphs (as well as those in issue 1 or 2) should be changed, especially if the specific KR glyphs are still kept in Revision 2.  This makes the font less consistent (and less pan-CJK) regarding its orthography.

**Comment by kenlunde** [comment] 2017-05-19 17:07
@hfhchan: The main focus of the KR glyphs is about consistency. KS standards and other character-related standards emanating from the southern Korean peninsula are notoriously inconsistent.

With that said, here is the result of my investigation:

The following 11 characters simply need to change their mapping from the JP glyph to the CN one in the KR CMap resource: U+60C6 惆, U+6E54 湔, U+83DF 菟, U+86C0 蛀, U+8729 蜩, U+8CD9 賙, U+90DC 郜, U+99B0 馰, U+9C4F 鱏, U+9D69 鵩, and U+9EF7 黷.

The following four characters need to change their mappings from the JP to the CN one in the KR CMap resource, and the JP glyph can be removed: U+5125 儥, U+58B0 墰, U+6D2C 洬, and U+83C2 菂.

The following character needs to change its mapping from the KR glyph to the CN one in the KR CMap resource, and the KR glyph can be removed: U+4E7C 乼.

A new KR glyph for U+970C 霌 needs to be added, and the JP glyph can be removed.

New KR glyphs for U+6424 搤, U+7662 癢, and U+9714 霔 need to be added.

I consider U+5C14 尔 to be a stylistic difference.

Your report also uncovered a small number of _Source Han Sans_ issues:

New KR glyphs for U+5070 偰, U+6424 搤, and U+7662 癢 need to be added.

The JP glyphs for U+6424 搤, U+7662 癢, and U+9746 靆 need to be modified.

**Comment by hfhchan** [comment] 2017-05-19 17:35
@kenlunde sigh.  Again a problem of "consistency with the standards" vs "consistency with the conventions".

**Comment by kenlunde** [comment] 2017-05-19 17:38
@hfhchan: In terms of lack of consistency, the V-source representative glyphs by far have the most problems. The inconsistency in the K-source representative glyphs is probably due to a lack of sensitivity. Anyway, once I note these issues in the appropriate consolidation issues, I will close this issue.

**Comment by kenlunde** [comment] 2017-05-20 04:09
Consolidated.

**Closed by kenlunde** 2017-05-20 04:09 UTC
Labels: consolidated
