### ISSUE TITLE
躍(U+8E8D)   hk與tw字形錯誤

### ISSUE THREAD

**Issue by jisbig5** [adobe-fonts/source-han-serif#207] opened 2023-12-05 13:51 UTC

**Comment by tamcy** [comment] 2023-12-05 14:59
This has been reported before in #155 (item B10).

**Comment by punchcutter** [comment] 2024-03-12 22:29
Duplicate of https://github.com/adobe-fonts/source-han-serif/issues/155

**Closed by punchcutter** 2024-03-12 22:29 UTC
