### ISSUE TITLE
Incorrect mapping for U+337F ㍿ in CN, TW and HK

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-serif#191] opened 2023-07-20 11:51 UTC
![image](https://github.com/adobe-fonts/source-han-serif/assets/33471049/b54ffacc-305e-4dab-9c58-dd8009e61019)

The 3 mappings for U+337F ㍿ in CN, TW and HK are using the vertical form instead of the horizontal form. This is a regression from v1.001. A sample character 返 is shown to make sure the font selected is correct.

*This may be ignored if #143 is accepted.*

**Comment by punchcutter** [comment] 2023-07-21 12:45
Dupe of https://github.com/adobe-fonts/source-han-serif/issues/143
The mapping problem is already mentioned in #143 so no need for this extra issue.

**Closed** 2023-07-21 12:46 UTC
