### ISSUE TITLE
Source Han Serif - Greek letter of 'theta'  (unicode: 03B8) is wrong, showing as a dark spot.

### ISSUE THREAD

**Issue by wangdong1226** [adobe-fonts/source-han-serif#137] opened 2021-11-21 01:57 UTC
The Greek small letter of 'theta' (unicode: 03B8) in **all Source Han Serif** sets fonts are as a dark spot, not the correct word of theta.
Please fix it among all Source Han Serif sets fonts. Thanks a lot!

In all Source Han Sans, it was correct, no problem.

![Greek - theta - unicode 03B8](https://user-images.githubusercontent.com/580076/142746769-db5d4ebd-2bf1-4e14-ab21-25f048faf2f9.png)

**Comment by wangdong1226** [comment] 2021-11-21 02:12
Sorry, I'm faild to upload the image into the link. Still trying....

**Comment by wangdong1226** [comment] 2021-11-21 02:19
Finally successfully upload the image. en......

**Comment by punchcutter** [comment] 2021-11-21 02:47
Duplicate of https://github.com/adobe-fonts/source-han-serif/issues/117

**Closed** 2021-11-21 02:47 UTC
Labels: duplicate
