### ISSUE TITLE
Wrong glyph for U+5177 具 字形错误

### ISSUE THREAD

**Issue by port16225** [adobe-fonts/source-han-serif#142] opened 2021-12-21 12:12 UTC
The glyph for U+5177 具 is wrong.
![u5177](https://user-images.githubusercontent.com/39243729/146927667-11bd41c6-4d81-4642-9553-d43f6c4ce2ab.png)
It's not 目 above 一，the strokes must stick to 一

U+5177 “具”字字形错误，不是“目”在“一”之上，必须连起来。现在的字形不符中国的语言文字规范。

**Comment by port16225** [comment] 2021-12-21 12:18
https://www.zdic.net/hans/%E5%85%B7
![ju2](https://user-images.githubusercontent.com/39243729/146928476-aae91470-e821-42f2-a758-540599299e83.png)
The glyph seems JP glyph. However, I only downloaded the CN fonts and only using CN fonts.
这个字形似乎是日本的字形，但是我只使用中国部分的字体，也只下载了CN部分的字体，可能字体制作者搞错了。

**Comment by punchcutter** [comment] 2021-12-21 12:55
The CN glyph was removed in 2.000 and replaced with uni5177uE0101-JP which is the same form, but the mapping didn't get updated properly. It has been fixed for the next release.

**Comment by port16225** [comment] 2021-12-21 13:03
> The CN glyph was removed in 2.000 and replaced with uni5177uE0101-JP which is the same form, but the mapping didn't get updated properly. It has been fixed for the next release.

Thank you!

**Comment by punchcutter** [comment] 2022-01-05 06:33
Duplicate of https://github.com/adobe-fonts/source-han-serif/issues/120

**Closed by punchcutter** 2022-01-05 06:33 UTC
Labels: fixed-for-next-release
